name: CI

on:
  push: 
    branches: [main]
  workflow_dispatch:

jobs:
  display: 
    runs-on: ubuntu-latest
    env: 
      platform: AWS
      region: eu-west-1
    steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-node@v2
     - name: Display env variables
       run: |
         echo "the platform is ${{ env.platform }}"
         echo "the region is ${{ env.region }}"
     - name: pwd
       run: | 
         pwd
     - name: ls
       run: | 
         ls -al
     - name: run 
       run: | 
         npm install
         npm run test --if-present