name: CI

on:
  push: 
    branches: [main]
  workflow_dispatch:

jobs:
  display: 
    runs-on: ubuntu-latest
    env: 
      platform: AWS
      region: eu-west-1
    steps:
     - name: Display env variables
       run: |
         echo "the platform is ${{ env.platform }}"
         echo "the region is ${{ env.region }}"
     - name: run 
       run: | 
         npm version
         npm install
         npm test 